import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import AppProvider from "../providers/AppProvider";
import "./globals.css";

const rubikFont = Rubik({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Aldi | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubikFont.className} antialiased bg-purple-50`}>
        <AppProvider>
          <div className="container">
            {children}
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
